[build]
builder = "NIXPACKS"
buildCommand = "npm install && NODE_OPTIONS=--openssl-legacy-provider npm run build"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
